# Generated by Django 4.1.3 on 2023-02-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_partiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ANA', 'Maths analyse'), ('DISC', 'Maths discrete'), ('STAT', 'Statistiques'), ('PROBA', 'Probabilité'), ('DJ', 'Django'), ('MGSI', 'Methode Agiles')], max_length=5)),
                ('mat_image', models.ImageField(upload_to='Cours')),
            ],
        ),
    ]
